# Generated by Django 4.0.5 on 2022-09-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_string', models.CharField(max_length=50)),
                ('string_1', models.CharField(max_length=50)),
                ('string_2', models.CharField(max_length=50)),
                ('string_3', models.CharField(max_length=50)),
                ('master_4', models.CharField(max_length=50)),
            ],
        ),
    ]
